### PR TITLE
Add `fbpic` example script [WIP]

### PR DESCRIPTION
**Pull request by berceanu**
This PR adds an example `fbpic` input script, based on [`lwfa_script.py`](https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/lwfa_script.py). The runtime on my laptop, using an NVIDIA GeForce GTX 950M is under 4 minutes.

To test it, install `fbpic` and do
```console
$ cd example
$ python fbpic_lwfa_script.py
```

### CODE REVIEW

**Comment by berceanu** [comment]
We might decide to remove this script later on, or it can be moved to `fbpic`, but for now it serves as good base for reproducible testing I think.

**Comment by hightower8083** [comment]
Hi @berceanu and thanx for this PR. 

I'll check it shortly, but this should be completed with the track-extraction, radiation calculation and some post-processing notebook in order to make it a workflow example rather than just a PIC run.

**Comment by berceanu** [comment]
Yes of course, this is still WIP and not ready for merging yet :) I put it up so I can get your feedback on the .h5 generation before continuing.

**Comment by berceanu** [comment]
I merged this into the other PR, closing.

**Pull request closed without merging**
